CREATE INDEX IDX_ITEM on ITEM (Item_id, Name);

CREATE INDEX IDX_CATEGORY on CATEGORT (CID, Small_category);

CREATE INDEX IDX_PRODUCERLOCATION on PRODUCERLOCATION (PID);

CREATE INDEX IDX_RETAILER on RETAILER (Store_idx);

CREATE INDEX IDX_CUSTOMER on CUSTOMER (User_id, Phone_number);

CREATE INDEX IDX_SHOPPINGBAG on SHOPPINGBAG (Bag_idx, User_id );

CREATE INDEX IDX_MANAGE on MANAGE (Store_idx, Item_id);

CREATE INDEX IDX_INCLUDE on INCLUDE (Bag_idx, User_id, Item_id);

CREATE INDEX IDX_ORDERED_BY on ORDERED_BY (Bag_idx, User_id);
